name: begoo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg:
  flutter_screenutil:
  easy_localization:
  hexcolor:
  shared_preferences:
  animated_splash_screen:
  cupertino_icons: ^1.0.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/2e398ce187b7ff530922f2bf823b0dba@2x.png
    - assets/images/5c536367e69f61bc55b07b5e4a7ca187.png
    - assets/images/7291a2e7b417e7a7271f456230ed58a0.png
    - assets/images/a2156c2ba9ad3984e9fa215070825d4f.png
    - assets/images/Apple.svg
    - assets/images/de71a3def8f0467613db684feb7e0de6.png
    - assets/images/f3b63d0224f3e0812238f81d9aca2b03.png
    - assets/images/fb.svg
    - assets/images/florian-klauer-nptLmg6jqDo-unsplash.png
    - assets/images/gmail.svg
    - assets/images/Group 2.png
    - assets/images/Group 2.svg
    - assets/images/hello-i-m-nik-F3E5Bkq0JUY-unsplash.png
    - assets/images/icon-2.svg
    - assets/images/icon.svg
    - assets/images/joshua-coleman-8V4y-XXT3MQ-unsplash.png
    - assets/images/logo.png
    - assets/images/logo.svg
    - assets/images/magnifying-glass.png
    - assets/images/markus-spiske-yftrRWzcSPU-unsplash.png
    - assets/images/nguyen-bui-Zx97aKIDnv4-unsplash.png
    - assets/images/noun_appreciation_3117367.png
    - assets/images/noun_Bell_1497524.png
    - assets/images/noun_cart_1533491.png
    - assets/images/noun_cart_1533491.svg
    - assets/images/noun_Email_681592.svg
    - assets/images/noun_Heart_19653.png
    - assets/images/noun_Heart_196534.png
    - assets/images/noun_Home_3496042.png
    - assets/images/noun_menu_1807546.png
    - assets/images/noun_Phone_1788724.svg
    - assets/images/noun_Settings_3496538.png
    - assets/images/noun_User_1150157.svg
    - assets/images/password.svg
    - assets/images/pexels-cottonbro-3661264.png
    - assets/images/pexels-cottonbro-3661353.png
    - assets/images/pexels-miguel-á-padriñán-194094.png
    - assets/images/pexels-pixabay-255514.png
    - assets/images/pexels-pixabay-459957.png
    - assets/images/rock-n-roll-monkey-LEPhZkQbUrk-unsplash.png
    - assets/images/sandy-millar-nuS2GDpCDoI-unsplash.png
    - assets/images/splash.png
    - assets/lang/ar.json
    - assets/lang/en.json
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
