/// Generated by AssetsRefGenerator on 2023/03/07
class Res {
  static const String ce187b7ff530922f2bf823b0dba =
      "assets/images/2e398ce187b7ff530922f2bf823b0dba@2x.png";
  static const String c536367e69f61bc55b07b5e4a7ca187 =
      "assets/images/5c536367e69f61bc55b07b5e4a7ca187.png";
  static const String a2e7b417e7a7271f456230ed58a0 =
      "assets/images/7291a2e7b417e7a7271f456230ed58a0.png";
  static const String a2156c2ba9ad3984e9fa215070825d4f =
      "assets/images/a2156c2ba9ad3984e9fa215070825d4f.png";
  static const String Apple = "assets/images/Apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String de71a3def8f0467613db684feb7e0de6 =
      "assets/images/de71a3def8f0467613db684feb7e0de6.png";
  static const String en = "assets/lang/en.json";
  static const String f3b63d0224f3e0812238f81d9aca2b03 =
      "assets/images/f3b63d0224f3e0812238f81d9aca2b03.png";
  static const String fb = "assets/images/fb.svg";
  static const String florian_klauer_nptLmg6jqDo_unsplash =
      "assets/images/florian-klauer-nptLmg6jqDo-unsplash.png";
  static const String gmail = "assets/images/gmail.svg";
  static const String Group = "assets/images/Group 2.png";
  static const String Groups = "assets/images/Group 2.svg";
  static const String hello_i_m_nik_F3E5Bkq0JUY_unsplash =
      "assets/images/hello-i-m-nik-F3E5Bkq0JUY-unsplash.png";
  static const String icon = "assets/images/icon.svg";
  static const String icon_2 = "assets/images/icon-2.svg";
  static const String joshua_coleman_8V4y_XXT3MQ_unsplash =
      "assets/images/joshua-coleman-8V4y-XXT3MQ-unsplash.png";
  static const String logo = "assets/images/logo.png";
  static const String logo3 = "assets/images/logo.svg";
  static const String magnifying_glass = "assets/images/magnifying-glass.png";
  static const String markus_spiske_yftrRWzcSPU_unsplash =
      "assets/images/markus-spiske-yftrRWzcSPU-unsplash.png";
  static const String nguyen_bui_Zx97aKIDnv4_unsplash =
      "assets/images/nguyen-bui-Zx97aKIDnv4-unsplash.png";
  static const String noun_appreciation_3117367 =
      "assets/images/noun_appreciation_3117367.png";
  static const String noun_Bell_1497524 = "assets/images/noun_Bell_1497524.png";
  static const String noun_cart_1533491 = "assets/images/noun_cart_1533491.png";
  static const String noun_cart_153341 = "assets/images/noun_cart_1533491.svg";
  static const String noun_Email_681592 = "assets/images/noun_Email_681592.svg";
  static const String noun_Heart_19653 = "assets/images/noun_Heart_19653.png";
  static const String noun_Heart_196534 = "assets/images/noun_Heart_196534.png";
  static const String noun_Home_3496042 = "assets/images/noun_Home_3496042.png";
  static const String noun_menu_1807546 = "assets/images/noun_menu_1807546.png";
  static const String noun_Phone_1788724 =
      "assets/images/noun_Phone_1788724.svg";
  static const String noun_Settings_3496538 =
      "assets/images/noun_Settings_3496538.png";
  static const String noun_User_1150157 = "assets/images/noun_User_1150157.svg";
  static const String password = "assets/images/password.svg";
  static const String pexels_cottonbro_3661264 =
      "assets/images/pexels-cottonbro-3661264.png";
  static const String pexels_cottonbro_3661353 =
      "assets/images/pexels-cottonbro-3661353.png";
  static const String pexels_migueln_194094 =
      "assets/images/pexels-miguel-á-padriñán-194094.png";
  static const String pexels_pixabay_255514 =
      "assets/images/pexels-pixabay-255514.png";
  static const String pexels_pixabay_459957 =
      "assets/images/pexels-pixabay-459957.png";
  static const String rock_n_roll_monkey_LEPhZkQbUrk_unsplash =
      "assets/images/rock-n-roll-monkey-LEPhZkQbUrk-unsplash.png";
  static const String sandy_millar_nuS2GDpCDoI_unsplash =
      "assets/images/sandy-millar-nuS2GDpCDoI-unsplash.png";
  static const String splash = "assets/images/splash.png";
}
